### PR TITLE
Enhancements to Pack Detection

### PR DESCRIPTION
**Pull request by JTK222**
This PR is not finished yet, I still have to add a few more features.
paintings json has to be in the root of a resource pack and called `paintings++.json`

### CODE REVIEW

**Comment by AbsolemJackdaw** [comment]
can it check for either paintings.json and paintings++.json ? that would allow backward compatibility with old packs

**Comment by JTK222** [comment]
Sure, can add that. Would suggest dropping paintings.json with 1.20 though, it's risky enough to have a json in the root of resource packs, so it's definitely best to have the name as specific as possible.

**Review by AbsolemJackdaw — APPROVED** [review]

**Comment by JTK222** [comment]
but.. but it was untested 👀

**Comment by AbsolemJackdaw** [comment]
oh shit

**Comment by AbsolemJackdaw** [comment]
I reverted it
you can continue to work on the branch

**Comment by AbsolemJackdaw** [comment]
let me see if i can reopen this

**Pull request merged**
