### PR TITLE
Compile master for 1.10.2

### PR DESCRIPTION
**Pull request by BookOfGreg**
For anyone else who wants to copy me, this is all that's needed to compile this mod for 1.10.2 from master(5ed400d)

### CODE REVIEW

**Comment by BookOfGreg** [comment]
I've been tinkering with asset packs and the new JSON format, seem to work well. Are there any open problems with it? I've managed to use the massive.json and massive.png and make changes to them both just fine.

**Comment by MurphysChaos** [comment]
The server-based configuration fails because the code is trying to use client-only calls to read the JSON file. I've been working on getting the server to be able to read the file from the config directory and pass that information to the client over the network.

**Comment by ArtixAllMighty** [comment]
We currently solved the issue by just warning the player on any differences between server (remote) and client.
We're concidering making servers down- and upload the differences, but I myself am afraid that it  might compromise the space some servers reserve. So a warning might be best. The code has been pushed and we're about to release a new version with this code. Feel free to check it

**Comment by ArtixAllMighty** [comment]
Marking it as obsolete. If you want to port to 1.10.2 , try to backport the latest 5.x.x.x, it has everything working.

**Pull request closed without merging**
